### ISSUE TITLE
Error: Invalid HEX color: "yellow"

### ISSUE THREAD

**Issue by Kotpes** [onury/invert-color#12]
I'm building an app, where color is provided by `data-` attribute and it can be anything that user types. There is a potential case that they'll type `"yellow"`instead of `"#ffff00"`.
Right now using this lib and color as word, will throw an error `Error: Invalid HEX color: "yellow" `
One possible solution I found is to map all cross-browser predefined colours to their hexadecimal counterpart:
https://stackoverflow.com/questions/1573053/javascript-function-to-convert-color-names-to-hex-codes/24390910
Do you think it'd be possible to include something like that into the lib itself?
PS Great module, by the way, super helpful!

**Comment by onury** [comment]
Thanks @Kotpes. First of, the error you get is proper since `"yellow"` is not a hexadecimal color code. 

And per your suggestion, I think it's better if you handle the conversion from known name to hex value (and vice-versa) in your app; and then pass it to invert method. This library targets both Node and browser and the color name list would increase the size significantly.
