### ISSUE TITLE
So does it invert brightness or only hue?

### ISSUE THREAD

**Issue by rugk** [onury/invert-color#13]
Your lib looks nice, but actually I am still not sure whether it inverts in the way I need it.

So here is the back story: In short, I need it [for my add-on](https://github.com/rugk/offline-qr-code), which wants to get the best _contrasting_ color for a given color, as it can otherwise not be scanned by QR code scanners.
As such [the first implementation](https://github.com/rugk/offline-qr-code/pull/86) turned out to [have a little issue](https://github.com/rugk/offline-qr-code/issues/117) being that it inverts the brightness, too.
I am still not really convinced whether this is good for my aim or not, but well...
Seeing this only inverting the hue seems to be a little more complicated, so I stumbled upon your lib ([here](https://stackoverflow.com/questions/1664140/js-function-to-calculate-complementary-colour) of course).

So back to my questions:
* So this is inverting only the hue, is not it?
* Maybe, you may add the feature to also invert the brightness, too? Or is there no actual use case for that?
* And may I be better off with using this lib and only the hue?

Generally my problem/use case of course would need [a very clever way to get the "best" contrast somehow](https://github.com/rugk/offline-qr-code/issues/92). If you have any tips/ideas, feel free to comment.

**Comment by rugk** [comment]
Also saw [this](https://stackoverflow.com/questions/6763032/how-to-pick-a-background-color-depending-on-font-color-to-have-proper-contrast/39277936), but this also does what you do with the bw option, as it seems. Just convert it to black or white only, which may not really be the best aesthetic color to suggest for a user.

**Comment by rugk** [comment]
Oh, no, you actually do the same as we: Also invert brightness, as it seems.

So maybe you can add a feature to only invert hue?

**Comment by onury** [comment]
Hi. This lib only inverts the hue as Adobe Photoshop does with its "invert" feature. There is a black/white option which checks if the luminance is over or below a threshold and returns a pre-defined dark or light color (by default black & white).

This is to be used for general cases targeted mainly for the human eye. 

For your use case (with QR scanners), I can only suggest to bump up either levels, curves or contrast so that it can distinguish the shapes better. Maybe convert to black/white or grayscale before you do so. AFAIK, QR scanners don't care for the colors.

**Comment by rugk** [comment]
Well… my use case is:
* provide a visually pleasing QR code display for the human user
* provide a working QR code for the "machine"

As such, i cannot just convert it to b/w. :smile:

**Comment by onury** [comment]
Fair enough. Closing this since it's not an issue with the lib. Thanks.
