### ISSUE TITLE
Fails for  #7f7f7f

### ISSUE THREAD

**Issue by nevf** [onury/invert-color#18]
If you pass in  `#7f7f7f`  you get back  `#7f7f7f` if `bw` is false.

IMO it's best to always use `bw`.

**Comment by onury** [comment]
See this [live test](https://runkit.com/onury/5c10e5e760841c00121ec4cc). It works as expected (returns `#808080`).
Make sure you're using the latest version.

**Comment by nevf** [comment]
@onury Thanks for the quick reply and yes you are right `#7f7f7f` returns `#808080`, however if I pass in `["128", "128", "128"]` then I get back `#7f7f7f` which is where I see the issue.

And I am using V2.0.0 just installed yesterday.

**Comment by onury** [comment]
@nevf RGB array `[128, 128, 128]` is represented as `#808080` in hexadecimal; which inverts to `#7f7f7f`. So the result is the expected value.

_Hint: Although a string array works, you should actually use number arrays for `RgbArray`._

**Comment by nevf** [comment]
@onury You are right again. :-) The issue is you can't see `#7f7f7f` on `#808080`, well at least I can't. :-)

**Comment by onury** [comment]
Ok, the reason is this:

You know, each RGB component can have a value between `0` to `255`.
`#808080` is exact mid-gray. So the inversion is very close to the input.

| Hex | RGB | Color |
| ---- | ---- | ------ |
| `#808080` | `[128, 128, 128]` | mid-gray |
| `#7f7f7f` | `[127, 127, 127]` | inverted mid-gray |

![invert-mid-gray-2](https://user-images.githubusercontent.com/3665990/49907897-32241400-fe89-11e8-91a8-d763e8cba3ea.jpg)

That's why I included an **amplfying to black/white** feature in the library.
There are other inversions that human eye cannot see the difference.
But the inversion is right. Adobe Photoshop also inverts `#808080` to `#7f7f7f`.

**Comment by nevf** [comment]
@onury Understood and thanks for your patience. I hadn't tried any color inversion code until yesterday, so I just needed a better understanding. Apologies for wasting your time.

**Comment by onury** [comment]
No worries at all. You're welcome.

**Comment by canbax** [comment]
Although this inversion might be right in adobe, in practice it is simply not right. These 2 colors `#808080` and `#7f7f7f` are almost the same. They are no where inverse of each other in human perception. I would expect from this library to solve this issue. Otherwise it is simply not trustable for random inputs

**Comment by onury** [comment]
It's a scientific inversion. Use the `bw` option.

**Comment by canbax** [comment]
> It's a scientific inversion. Use the `bw` option.

I think it would be better to use w3c recommendations for the contrast of colors and finding the color with the most constrast. But anyway even their own formulas are questionable https://github.com/w3c/wcag3/issues/192

**Comment by Myndex** [comment]
Hi @canbax Hi @onury 

I stumbled on this as it is linking to another thread I am involved in (695 on WCAG) Just wanted to make a couple very brief comments. 

> > >  _each RGB component can have a value between 0 to 255. #808080 is exact mid-gray._ 

Well not really. Though I am not certain what you are trying to do here, it is true that #808080 is the middle of the sRGB 8 bit code values.

But that is not _perceptual_ middle grey. Perceptual middle per CIELAB is #777777,(in theory) which is luminance 0.184Y (i.e. 18%) or Zone V (Adams), based on linearizing sRGB using the piecewise TRC (the IEC standard sets threshold at 0.04045, not 0.03928 which was in an obsolete draft).

**But there's more:** the 18% grey that is oft assumed/accepted as middle grey does not apply to emissive monitors in most situations. Our research finds "middle contrast grey" roughly between #999999 and #a6a6a6 depending on the ambient lighting.

The upshot is, if you are looking for a place to "flip" text color from black to white, against some background color's luminance, luminance 0.35Y (35%) is about the point that black text and white text have the same perceived contrast. There are still variations, as I mentioned, ambient light, but also the hue and saturation of the color can change apparent contrast, though luminance is by far the stronger contrast.

> > _Although this inversion might be right in adobe, in practice it is simply not right._ 
> _It's a scientific inversion._ 

A dough bee is a little odd when it comes to some of these things. While they have a lot of useful features, don't assume that all are perceptually uniform or correct as many are not. I.e. don't assume that a PS invert is perceptually correct.

A lot of the features are still around since the legacy app, and did not use perceptual methods, operating only on the gamma encoded RGB channels. The true perceptual inverse of a color is not 255-c, though that is a fast way to get an approximation. 

A true inverse would need to be in a uniform appearance model space, like CIECAM02. 


> _I think it would be better to use w3c recommendations for the contrast of colors and finding the color with the most constrast. But anyway even their own formulas are questionable [w3c/wcag3#192](https://github.com/w3c/wcag3/issues/192)_

The formula for WCAG 2 is known to be incorrect in a number of use cases. WCAG 3 is/will be using the much newer and much improved APCA (Advanced Perceptual Contrast Algorithm). There is more information at the [APCA git hub repo](https://github.com/Myndex/SAPC-APCA).

https://github.com/Myndex/SAPC-APCA

**Comment by canbax** [comment]
Thank you @Myndex You explanations are very informative and useful. I have a small question. [Here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_Colors_and_Luminance#perceptual_lightness) it says human perception is not linear but a power curve (L* = Y<sup>0.425</sup>). So why don't we use this power curve in the contrast calculation formula? `((L1 + 0.05)/(L2 + 0.05))` It is better to use power curve?

**Comment by Myndex** [comment]
Hi @canbax 

> ....says human perception is not linear but a power curve (L* = Y0.425). So why don't we use this power curve in the contrast calculation formula? `((L1 + 0.05)/(L2 + 0.05))` It is better to use power curve?

I had no involvement with WCAG 2.x contrast and I had nothing to do with the formula  `((L1 + 0.05)/(L2 + 0.05))`  I am on record in [issue 695 ](https://github.com/w3c/wcag3/issues/192) regarding the problems of a lack of perceptual uniformity in the 2.x method and I don't support it as a useful method, and really don't discuss it much, and I can't answer "why". My focus is on the future and the APCA as the new method.

APCA uses power curves as part of the model.

**Comment by canbax** [comment]
I get inspiration from here I developed a small library for finding contrasting colors. It does not fail for #7f7f7f https://github.com/canbax/contra-color When finding color you can also put a threshold to contrast difference.
